services: 
  - mongodb
  - elasticsearch

notifications:
  email: false

language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - jruby-20mode

gemfile:
  - Gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/es-git.gemfile
  - gemfiles/es-0.4.1.gemfile
