services: 
  - mongodb
  - elasticsearch

notifications:
  email: false

language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head

gemfile:
  - Gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/es-git.gemfile

# mongoid 4 has problems
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode