services: 
  - mongodb
  - elasticsearch

notifications:
  email: false

language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - jruby-21mode

gemfile:
  - Gemfile
  - gemfiles/mongoid3.gemfile
  - gemfiles/es-git.gemfile
